### ISSUE TITLE
Migrate to Arduino Environment

### ISSUE THREAD

**Issue by Lauren-ED209** [evilwombat/stm32f103_fastNP#1]
Dear friend,

Thanks for your great effort.
I‘m developing a gaming laptop with x86 factories. I want to use STM32F103(for low cost and stable supply chain) + Arduino + WS2812b for backlight strip control. And multi channels control is pretty necessary for me! 
I've worked with Arduino for 10 years. However I've almost forget how to build a project from c. 
So would you mind to share some simple steps for me and lead me to migrate this project to Arduino environment!? 

Look forward to your suggestion!

Best,
Lauren

**Comment by evilwombat** [comment]
Historically, getting Arduino up and running for me has been a pain in the neck. The Arduino stuff tends to trade one set of problems for another set of problems. In my project, you need to follow the instructions for setting up STM32 CubeMX using the ARM GCC toolchain. Then you go into my top-level project and run "make" and you'll get a binary. I'll take a look at the Arduino stuff, see how far I get.... just got my board to finally flash using their bootloader, so.. here we go

**Comment by evilwombat** [comment]
Wow, what a mess.... the problem is that the Arduino environment does not contain the STM32 CubeMX HAL, which my code requires.

But I actually managed to get it working!

Need to clean it up - I am including WAY more 
of the HAL than I need. It looks like the HAL's Delay() functionality is broken, but luckily I only use that in the beginning of my demo, the rest of the code uses only direct timer access and polling. So..... this should be doable. Need to do it before the neighbors wake up, or they get noisy and I can't get anything done :)

**Comment by evilwombat** [comment]
Okay, I got it working. It was a little messy because Arduino does not include the STM32 CubeMX HAL, so I had to port over the parts that were necessary.

**Comment by evilwombat** [comment]
Here is the Arduino port:
https://github.com/evilwombat/stm32f103_fastNP_Arduino

**Comment by Lauren-ED209** [comment]
Wow. Awesome! I will test it next week and update my testing result here ASAP.
Thanks for your great contribution!

**Comment by Lauren-ED209** [comment]
Thanks for your contribution. I've tested it with Arduino_STM32 repo environment, which works perfectly for me. 

Thank you again. My friend!
